#!/bin/bash
#SBATCH --account=sq72
#SBATCH --time=04:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=2048
#SBATCH --cpus-per-task=12

env_id=$1
alpha=$2
beta=$3
gamma=$4
delta=$5

output_path=./slurm_stdout/tests/${env_id}_${alpha}${beta}${gamma}${delta}_%j.log

sbatch --job-name=test_${env_id}_$alpha$beta$gamma$delta --output=$output_path --export All,env_id=$env_id,alpha=$alpha,beta=$beta,gamma=$gamma,delta=$delta test.sh
